#pragma once

#include "evtmgr.h"

#include <cstdint>

namespace ttyd::evt_mario {

extern "C" {

EVT_DECLARE_USER_FUNC(evt_mario_paper_plane, 1)
EVT_DECLARE_USER_FUNC(L_evt_mario_keyon_wait, 0)
EVT_DECLARE_USER_FUNC(evt_mario_get_name_hitobj_push, 1)
EVT_DECLARE_USER_FUNC(evt_mario_get_name_hitobj_front, 1)
EVT_DECLARE_USER_FUNC(evt_mario_get_name_hitobj_under, 1)
EVT_DECLARE_USER_FUNC(evt_mario_get_name_hitobj_ride, 1)
EVT_DECLARE_USER_FUNC(evt_mario_get_name_hitobj_head, 1)
EVT_DECLARE_USER_FUNC(evt_mario_dump_item, 1)
EVT_DECLARE_USER_FUNC(evt_mario_check_key_item, 2)
EVT_DECLARE_USER_FUNC(evt_mario_sleep_off, 0)
EVT_DECLARE_USER_FUNC(evt_mario_sleep_on, 0)
EVT_DECLARE_USER_FUNC(evt_mario_push, 0)
EVT_DECLARE_USER_FUNC(evt_mario_clear_party, 1)
EVT_DECLARE_USER_FUNC(evt_mario_kill_party, 1)
EVT_DECLARE_USER_FUNC(evt_mario_goodbye_party, 1)
EVT_DECLARE_USER_FUNC(evt_mario_set_prev_party_pos, 4)
EVT_DECLARE_USER_FUNC(evt_mario_set_prev_party, 1)
EVT_DECLARE_USER_FUNC(evt_mario_set_party_pos, 5)
EVT_DECLARE_USER_FUNC(evt_mario_set_party, 2)
EVT_DECLARE_USER_FUNC(evt_mario_hello_exparty_pos, 4)
EVT_DECLARE_USER_FUNC(evt_mario_hello_party, 2)
EVT_DECLARE_USER_FUNC(evt_mario_set_prev_party_dokan, 1)
EVT_DECLARE_USER_FUNC(evt_mario_party_use_check, 1)
EVT_DECLARE_USER_FUNC(evt_mario_chk_join_party, 2)
EVT_DECLARE_USER_FUNC(evt_mario_get_exparty, 1)
EVT_DECLARE_USER_FUNC(evt_mario_get_party, 1)
EVT_DECLARE_USER_FUNC(evt_peach_set_condition, 1)
EVT_DECLARE_USER_FUNC(evt_peach_transform_gundan_off, 0)
EVT_DECLARE_USER_FUNC(evt_peach_transform_gundan_on, 0)
EVT_DECLARE_USER_FUNC(evt_koopa_set_level, 1)
EVT_DECLARE_USER_FUNC(evt_koopa_get_level, 1)
EVT_DECLARE_USER_FUNC(evt_mario_set_mode, 1)
EVT_DECLARE_USER_FUNC(evt_mario_get_mode, 1)
EVT_DECLARE_USER_FUNC(evt_mario_get_state, 1)
EVT_DECLARE_USER_FUNC(evt_mario_wait_movable, 0)
EVT_DECLARE_USER_FUNC(evt_mario_wait_move_end, 0)
EVT_DECLARE_USER_FUNC(evt_koopa_weary, 1)
EVT_DECLARE_USER_FUNC(evt_koopa_chk_dead, 1)
EVT_DECLARE_USER_FUNC(evt_koopa_fire, 1)
EVT_DECLARE_USER_FUNC(evt_koopa_hip_attack, 5)
EVT_DECLARE_USER_FUNC(evt_mario_check_landon, 1)
EVT_DECLARE_USER_FUNC(evt_mario_wait_rideon, 0)
EVT_DECLARE_USER_FUNC(evt_mario_wait_landon, 0)
EVT_DECLARE_USER_FUNC(evt_mario_jump_jumpstand, 11)
EVT_DECLARE_USER_FUNC(evt_mario_jump_pos, 6)
EVT_DECLARE_USER_FUNC(evt_mario_party_bero_move, 3)
EVT_DECLARE_USER_FUNC(evt_mario_party_door_move, 3)
EVT_DECLARE_USER_FUNC(N_evt_mario_party_door_halve_hitbox, 0)
EVT_DECLARE_USER_FUNC(evt_mario_mov_pos2, 3)
EVT_DECLARE_USER_FUNC(evt_mario_mov_pos, 3)
EVT_DECLARE_USER_FUNC(evt_mario_set_force_dir, 1)
EVT_DECLARE_USER_FUNC(evt_mario_get_pose, 1)
EVT_DECLARE_USER_FUNC(evt_mario_cancel_roll_motion, 0)
EVT_DECLARE_USER_FUNC(evt_mario_set_talk_motion, 0)
EVT_DECLARE_USER_FUNC(evt_mario_chk_hipbump, 1)
EVT_DECLARE_USER_FUNC(evt_mario_set_motion, 1)
EVT_DECLARE_USER_FUNC(evt_mario_get_motion, 1)
EVT_DECLARE_USER_FUNC(evt_mario_normalize, 0)
EVT_DECLARE_USER_FUNC(evt_mario_set_pose, 1)
EVT_DECLARE_USER_FUNC(evt_mario_set_normal_pose, 0)
EVT_DECLARE_USER_FUNC(evt_mario_adjust_dir, 0)
// unk_JP_US_EU_26_800e6b1c
EVT_DECLARE_USER_FUNC(evt_mario_set_dir_npc, 1)
EVT_DECLARE_USER_FUNC(evt_mario_set_dispdir, 1)
EVT_DECLARE_USER_FUNC(evt_mario_get_dispdir, 1)
EVT_DECLARE_USER_FUNC(evt_mario_set_reardir, 0)
EVT_DECLARE_USER_FUNC(evt_mario_set_dir, 3)
EVT_DECLARE_USER_FUNC(evt_mario_get_dir, 1)
EVT_DECLARE_USER_FUNC(evt_mario_get_mov_spd, 1)
EVT_DECLARE_USER_FUNC(evt_mario_set_mov_spd, 1)
EVT_DECLARE_USER_FUNC(evt_mario_set_hosei_xyz, 3)
EVT_DECLARE_USER_FUNC(evt_mario_set_pos, 3)
EVT_DECLARE_USER_FUNC(evt_mario_get_pos, 4)
EVT_DECLARE_USER_FUNC(evt_mario_set_camid, 1)
EVT_DECLARE_USER_FUNC(evt_mario_init_camid, 0)
EVT_DECLARE_USER_FUNC(evt_mario_cam_y_off, 0)
EVT_DECLARE_USER_FUNC(evt_mario_cam_y_on, 0)
EVT_DECLARE_USER_FUNC(evt_mario_cam_keep_off, 0)
EVT_DECLARE_USER_FUNC(evt_mario_cam_keep_on, 0)
EVT_DECLARE_USER_FUNC(evt_mario_cam_off, 0)
EVT_DECLARE_USER_FUNC(evt_mario_cam_on, 0)
EVT_DECLARE_USER_FUNC(evt_mario_bgmode_off, 0)
EVT_DECLARE_USER_FUNC(evt_mario_bgmode_on, 0)
EVT_DECLARE_USER_FUNC(evt_mario_set_enable_key, 1)
EVT_DECLARE_USER_FUNC(evt_mario_key_onoff, 1)
EVT_DECLARE_USER_FUNC(evt_mario_cont_onoff, 1)
EVT_DECLARE_USER_FUNC(evt_mario_trigflag_onoff, 2)
EVT_DECLARE_USER_FUNC(evt_mario_dispflag_onoff, 2)
EVT_DECLARE_USER_FUNC(evt_mario_flag_onoff, 2)
EVT_DECLARE_USER_FUNC(evt_mario_balloon_off, 0)
EVT_DECLARE_USER_FUNC(evt_mario_balloon_tenten, 0)
EVT_DECLARE_USER_FUNC(evt_mario_balloon_bikkuri, 0)
EVT_DECLARE_USER_FUNC(evt_mario_paper_pose_off, 0)
EVT_DECLARE_USER_FUNC(evt_mario_dokan_end, 0)
EVT_DECLARE_USER_FUNC(evt_mario_paper_pose_dokan, 1)
EVT_DECLARE_USER_FUNC(evt_mario_dokan_prepare, 1)

}

}